# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Season 2014"
email: "devfest@gdg.pe"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "http://devfestlima.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Lima"
organizerAlternateName: "Google Developer Group Lima"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Expositores"}
 
# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevFest Lima <typeout> 2014"
eventDate: "8 Noviembre, 2014"
typeoutTextValues: '"", "Sesiones", "Conferencia", "Talleres"'
typeoutFallback: "Season"
heroButtons:
 - {permalink: "/#tickets", text: "Obten tu entrada"}

# About Block
aboutTitle: "GDG DevFest Lima"
aboutBlock:
 - {title: "Conferencia", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lot's of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day free-style hackaton! Want some real teambuilding on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:

 - {count: "16", specialCharacter: "+", info: "horas", detail: "de tecnologia google"}
 - {count: "4", specialCharacter: "+", info: "expositores", detail: "de diferentes cuidades"}
 - {count: "2", specialCharacter: "", info: "sesiones en paralelo", detail: "de entretenimiento"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "Universidad Ricardo Palma"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Av. Benavidades 5440 Santiago de Surco"
eventAddressLocality: "Lima"
eventAddressLocalityRegion: "Lima"
eventPostalCode: "0073"
eventAddressCountry: "URP"
eventStartTime: "2014-11-08T09:00"
eventDoorTime: "09:00"
eventEndTime: "2014-11-08T20:00"
eventPlaceCoordinates: "-12.132417,-76.97978760000001"
mapCenterCoordinates: "-12.132417,-76.97978760000001"
mapMobileCenterCoordinates: "-12.132417,-76.97978760000001"

# Venue Block
venueBlockTitle: "Salas"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Auditorio A"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "¿Interactua con nosotros?"
twitterHashTag: "devfestlima"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"





# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/+gdglimape/posts", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=gdglima", icon: "twitter"}
 - {link: "https://facebook.com/gdglima", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlace"
  links:
   - {link: "http://gdglima.pe", text: "GDG Lima"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:gdglima@devfestlima.pe", text: "gdglima@devfestlima.pe"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}


# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Acerca de nosotros"
aboutUs: "Somos 3 capitulos de Desarrolladores de Google en Perú. Nuestra misión compartir conocimiento sobre tecnologias google."

